### ISSUE TITLE
Method add of DyTasks fail

### ISSUE THREAD

**Issue by oruam85** [yegor256/thindeck#492]
The method add of the DyTasks class return this error:

```
java.lang.IllegalStateException: java.io.IOException: java.sql.SQLException: org.h2.jdbc.JdbcSQLException: Column "COMM" not found; SQL statement:
INSERT INTO tasks (comm,id,urn) VALUES (?,?,?) [42122-176]
	at com.jcabi.dynamo.mock.MkTable.put_aroundBody0(MkTable.java:84)
	at com.jcabi.dynamo.mock.MkTable$AjcClosure1.run(MkTable.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.mock.MkTable.put(MkTable.java:80)
	at com.thindeck.dynamo.DyTasks.add(DyTasks.java:113)
	at com.thindeck.dynamo.DyTasksTest.addTaskWithoutAttributes(DyTasksTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: java.sql.SQLException: org.h2.jdbc.JdbcSQLException: Column "COMM" not found; SQL statement:
INSERT INTO tasks (comm,id,urn) VALUES (?,?,?) [42122-176]
	at com.jcabi.dynamo.mock.H2Data.put_aroundBody2(H2Data.java:225)
	at com.jcabi.dynamo.mock.H2Data$AjcClosure3.run(H2Data.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.mock.H2Data.put(H2Data.java:211)
	at com.jcabi.dynamo.mock.MkTable.put_aroundBody0(MkTable.java:82)
	... 31 more
Caused by: java.sql.SQLException: org.h2.jdbc.JdbcSQLException: Column "COMM" not found; SQL statement:
INSERT INTO tasks (comm,id,urn) VALUES (?,?,?) [42122-176]
	at com.jcabi.jdbc.JdbcSession.run(JdbcSession.java:403)
	at com.jcabi.jdbc.JdbcSession.execute_aroundBody16(JdbcSession.java:334)
	at com.jcabi.jdbc.JdbcSession$AjcClosure17.run(JdbcSession.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.jdbc.JdbcSession.execute(JdbcSession.java:334)
	at com.jcabi.dynamo.mock.H2Data.put_aroundBody2(H2Data.java:223)
	... 38 more
Caused by: org.h2.jdbc.JdbcSQLException: Column "COMM" not found; SQL statement:
INSERT INTO tasks (comm,id,urn) VALUES (?,?,?) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.command.Parser.parseColumn(Parser.java:849)
	at org.h2.command.Parser.parseColumnList(Parser.java:833)
	at org.h2.command.Parser.parseInsert(Parser.java:1033)
	at org.h2.command.Parser.parsePrepared(Parser.java:402)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at com.jcabi.jdbc.Connect$Plain.open(Connect.java:75)
	at com.jcabi.jdbc.JdbcSession.run(JdbcSession.java:383)
	... 46 more

```

Remember remove the Ignore annotation od the test addTaskWithAttributes and addTaskWithoutAttributes

**Comment by yegor256** [comment]
@oruam85 can you give a Java code example that reproduces this?

**Comment by oruam85** [comment]
@yegor256  the test:

```
final Repo repo = new MkRepo();
    	final Region region = DyTasksTest.region(repo.name());
    	final String command = "command";
    	
    	DyTasks tasks = new DyTasks(region, repo);
    	Map <String,String> map = new HashMap<String,String>();
    	Task task = tasks.add(command,map);
    	
    	MatcherAssert.assertThat(task.command(),Matchers.equalTo(command));
```

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@oruam85 thanks for the ticket, your account was topped for 15 mins, payment 50003557

**Comment by davvd** [comment]
@maxim-kornienko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by maxim-kornienko** [comment]
@davvd @oruam85 Done in pull request #512

**Comment by davvd** [comment]
@maxim-kornienko this task is in your hands for 15 days already; -30 added to your rating, at the moment it is: +105

**Comment by maxim-kornienko** [comment]
@davvd I has been done a while ago, see my comment. You can close it.

**Comment by oruam85** [comment]
@maxim-kornienko thanks. This bug is closed now

**Comment by davvd** [comment]
@maxim-kornienko I added **30 mins** to your account, many thanks for working with the project!. +30 added to your rating, current score is: +105
