### ISSUE TITLE
The get method in DyTasks fail

### ISSUE THREAD

**Issue by oruam85** [yegor256/thindeck#493]
If i try call the get method with a id that not exist return this error:

```
java.util.NoSuchElementException
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.thindeck.dynamo.DyTasks.get(DyTasks.java:94)
	at com.thindeck.dynamo.DyTasksTest.getTask(DyTasksTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Inclide the test of this case to DyTasksTest class

**Comment by yegor256** [comment]
@oruam85 can you give a Java code that reproduces this issue?

**Comment by oruam85** [comment]
@yegor256 use the test but with another id. 

``` 
final Repo repo = new MkRepo();
final long tid = 10L; 
MatcherAssert.assertThat( 
           new DyTasks(
                DyTasksTest.region(repo.name(), tid, 2L, 1L),
                repo
            ).get(20L).number(),
            Matchers.equalTo(tid)
        );
```

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@oruam85 thanks for reporting! I topped your account for 15 mins, transaction 50004746

**Comment by davvd** [comment]
@marczeeee this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by Marczeeee** [comment]
@oruam85 Related pull request #507 was merged. I think this issue can be closed.

**Comment by oruam85** [comment]
@Marczeeee Thanks. Closed

**Comment by davvd** [comment]
@marczeeee done, I added **30 mins** in payment `50617699`

+30 added to your rating, at the moment it is: +180
